version: "3"

services:
  lamindb:
    build:
      context: ./
    environment:
      - GRANT_SUDO=yes
    volumes:
      - ./:/home/jovyan
      - ~/.aws:/home/jovyan/.aws
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser
    ports:
      - 8888:8888
