version: "3"

services:
  lamin:
    build:
      context: ./
    environment:
      - GRANT_SUDO=yes
      - LAMIN_PASSWORD
      - AWS_PROFILE=lamin
      - AWS_DEFAULT_REGION
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_CREDENTIAL_EXPIRATION
    volumes:
      - ./:/home/jovyan
      - ~/.aws:/home/jovyan/.aws
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser
    ports:
      - 8888:8888
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: lamin
      POSTGRES_PASSWORD: lamin_pw
      POSTGRES_DB: lamindb
    command: postgres -c stats_temp_directory=/tmp
    ports:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  # minio:
  #   image: minio/minio:latest
  #   environment:
  #     - MINIO_ROOT_USER=lamin
  #     - MINIO_ROOT_PASSWROD=lamin_pw
  #   volumes:
  #     - ./volumes/minio:/data
  #   command: "minio server /data --console-address :9090"
  #   ports:
  #     - 9090
  #     - 9001

