name: Publish to ghcr

on:
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom tag for the image'
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: lamin-default

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        dockerfile:
          - configurations/bionty-jupyter/Dockerfile
          - configurations/aws-bionty-jupyter-postgres/Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set image name based on Dockerfile
        id: set_image_name
        run: |
          if [ "${{ matrix.dockerfile }}" == "configurations/bionty-jupyter/Dockerfile" ]; then
            echo "IMAGE_NAME=lamin/lamin-bionty-jupyter" >> $GITHUB_ENV
          elif [ "${{ matrix.dockerfile }}" == "configurations/aws-bionty-jupyter-postgres/Dockerfile" ]; then
            echo "IMAGE_NAME=lamin/lamin-aws-bionty-jupyter-postgres" >> $GITHUB_ENV
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        env:
          DOCKER_BUILDKIT: 1
